In [1]:
import pandas as pd
import numpy as np
import warnings
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('crop_recommendation_test.csv')
df

     Unnamed: 0    N   P   K  temperature   humidity        ph    rainfall   y
0            99   65  37  40    23.359054  83.595123  5.333323  188.413665  20
1          1337  117  27  48    26.532593  82.390540  6.835268   54.306608  21
2           316   22  79  17    21.424511  20.396597  5.912290  116.520692   9
3           985   39  25  36    18.902230  94.998975  5.567805  107.610321  19
4           471    5  77  19    31.085650  66.688330  6.242052  175.930327  18
..          ...  ...  ..  ..          ...        ...       ...         ...  ..
215        1708   38  68  54    29.337105  90.817814  6.739170  202.057275  17
216         275   27  79  82    17.065793  17.540241  6.307005   70.871506   3
217        1868    8  26  26    25.547599  91.641948  5.702485  212.867626   4
218         721   25  71  24    28.495387  60.448484  7.187722   74.915595   2
219        1151   21  31  32    35.385987  51.426642  5.254532   90.296439  12

[220 rows x 9 columns]

In [3]:
df_train, df_test, y_train, y_test = train_test_split(df.iloc[:,1:-1], df.iloc[:,-1], test_size=0.2, random_state=42)

In [4]:
df_test

       N    P    K  temperature   humidity        ph    rainfall
132   17   18   43    24.488084  90.836872  5.843005  103.196934
148   98   44   21    25.771751  74.089114  6.524478  107.493192
93   112   39   29    26.124922  63.374792  6.726529  147.803530
180   63   58   22    18.254054  55.282204  6.204748   63.723582
15    95   82   48    27.394896  83.311720  5.719015   92.781336
115   90   16   45    24.920933  80.617508  6.291540   50.557108
172    0   65   24    28.495844  62.446162  7.841496   53.145310
209   37   57   20    31.100625  44.820692  7.354287   70.799345
75    47   79   78    17.483954  14.760145  6.609697   65.113656
142   93   56   36    24.014976  82.056872  6.984354  185.277339
100    1   15    9    29.983647  94.552397  7.533509  115.356032
30    49   69   82    18.315615  15.361435  7.263119   81.787105
190   17   74   17    26.030270  69.558631  7.393211   37.113958
9     36   29   13    20.681852  90.915105  7.829507  109.751393
67   108   33   31    23.692871  66.760901  7.393826  144.657642
218   25   71   24    28.495387  60.448484  7.187722   74.915595
175   76   54   45    24.294966  77.629760  6.176619  184.980052
18   105   95   50    27.333690  83.676752  5.849076  101.049479
197   39   17   45    18.096911  90.421774  6.924491  104.881890
66    74   40   40    25.138428  83.120539  6.386260  169.338847
189   16   14   30    29.709313  96.304843  6.374668  209.845399
96    17   59   17    18.416700  23.428299  5.689858  132.980105
210   32  139  198    35.893075  82.668507  6.358187   66.539466
25     0   27   38    22.445813  89.901470  6.738016  109.390600
127   66   47   36    24.854414  74.440705  6.572561  175.572958
201   29    8   28    26.870376  91.725463  6.100429  214.412887
97    23   39   22    29.256493  81.979522  6.864839   42.024833
16    44   55   25    29.632105  65.913600  7.421608   71.163320
45    12   80   19    21.910410  65.216625  5.962001   36.102114
154   25   78   76    17.480426  15.755940  7.228963   66.969806
111   44   60   55    34.280461  90.555616  6.825371   98.540477
55   102   11   45    29.031673  93.126032  6.355443   24.155912
108  112   49   25    25.689595  77.906210  6.470135   66.194268
196  102   14   52    26.794899  89.648152  6.510760   57.740918
73    36   56   83    18.897802  19.761829  7.452671   69.095125
109   23    6   33    29.180326  92.730412  6.025790  204.960368
82    94   50   19    23.303553  73.625484  5.873242   97.590813
138   22   38   31    31.533564  53.060093  5.821106   98.570250
141   95   30   52    29.480699  90.336987  6.640471   26.036577
101   18   19   27    27.755187  52.346058  4.772386   94.112133
86    99   38   21    22.883309  71.597224  6.352472   67.727773
193   29   45   16    28.436835  87.913327  6.583382   43.120633
120   77   55   43    25.499417  75.999876  6.663559  193.714183
95    57   57   51    39.017933  91.488156  6.992234  105.884153

In [5]:
df_train

       N    P    K  temperature   humidity        ph    rainfall
79    71   54   16    22.613600  63.690706  5.749914   87.759539
217    8   26   26    25.547599  91.641948  5.702485  212.867626
113   38  132  197    20.420948  81.541850  5.931102   66.930657
140   86    6   53    25.920302  83.472026  6.921848   42.106815
122   40   73   20    21.593430  20.318712  5.811314   61.138720
..   ...  ...  ...          ...        ...       ...         ...
106  133   57   19    23.542347  75.982033  7.947011   84.125367
14   117   19   55    28.803119  91.783369  6.121745   25.163599
92    24   37   21    30.573999  58.226868  5.818219   62.748038
179  101   25   52    29.099104  94.222378  6.750146   22.524973
102   61   59   17    23.338446  59.245806  6.474443  105.008314

[176 rows x 7 columns]

In [6]:
y_test

132    19
148    11
93      5
180    11
15      1
115    21
172    10
209    13
75      3
142    20
100    16
30      3
190    10
9      16
67      5
218     2
175     8
18      1
197    19
66      8
189     4
96      9
210     7
25     19
127     8
201     4
97     14
16      2
45     10
154     3
111    17
55     15
108     6
196    21
73      3
109     4
82     11
138    12
141    15
101    12
86     11
193    14
120     8
95     17
Name: y, dtype: int64

In [7]:
y_train

79     11
217     4
113     7
140    21
122     9
       ..
106     6
14     15
92     13
179    15
102    11
Name: y, Length: 176, dtype: int64

In [8]:
model = RandomForestClassifier()
model.fit(df_train, y_train)

RandomForestClassifier()

In [9]:

pred = model.predict(df_test)
actual = np.array(y_test)
actual

array([19, 11,  5, 11,  1, 21, 10, 13,  3, 20, 16,  3, 10, 16,  5,  2,  8,
        1, 19,  8,  4,  9,  7, 19,  8,  4, 14,  2, 10,  3, 17, 15,  6, 21,
        3,  4, 11, 12, 15, 12, 11, 14,  8, 17], dtype=int64)

In [10]:
print("Accuracy:", model.score(df_test, y_test))

Accuracy: 0.9545454545454546

In [11]:
label_name = pd.read_csv('label_name_number.csv').iloc[:,1:]
label_name

      crop_name  Crop_number
0         apple            0
1        banana            1
2     blackgram            2
3      chickpea            3
4       coconut            4
5        coffee            5
6        cotton            6
7        grapes            7
8          jute            8
9   kidneybeans            9
10       lentil           10
11        maize           11
12        mango           12
13    mothbeans           13
14     mungbean           14
15    muskmelon           15
16       orange           16
17       papaya           17
18   pigeonpeas           18
19  pomegranate           19
20         rice           20
21   watermelon           21

In [14]:
sample_idx = np.random.randint(0, len(df_test))
res = model.predict([df_test.iloc[1].tolist()])
print(int(res))
if int(res) in label_name['Crop_number'].values:
    index_number = label_name.index[label_name['Crop_number'] == int(res)].tolist()[0]
    crop_name = label_name['crop_name'].iloc[index_number]
    print("crop_name:-> ", crop_name)

11
crop_name:->  maize